name: flutter_forge_workspace
description: Flutter Forge workspace container.
publish_to: 'none'

environment:
  sdk: ^3.11.5

workspace:
  - apps/flutter_forge
  - packages/file_picker_bridge
  - packages/flutter_ioc_core
  - packages/desktop_multi_window
