// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT

import 'package:flutter/foundation.dart';
import 'package:go_router/go_router.dart';

import '../module_home_page.dart';
import '../../module_registry/module_category.dart';
import '../../module_registry/module_catalog_utils.dart';
import '../../module_registry/module_entry.dart';
import '../../modules/basic/debounce_throttle/module_entry.dart';
import '../../modules/basic/microtask/module_entry.dart';
import '../../modules/basic/microtask/module_routes.dart';
import '../../modules/basic/tree_state/module_entry.dart';
import '../../modules/basic/tree_state/module_routes.dart';

import '../../modules/async/isolate_basic/module_entry.dart';
import '../../modules/async/isolate_basic/module_routes.dart';
import '../../modules/async/isolate_task_manager/module_entry.dart';
import '../../modules/async/stream_subscription/module_entry.dart';
import '../../modules/async/stream_subscription/module_routes.dart';

import '../../modules/state/flutter_ioc/module_entry.dart';
import '../../modules/state/status_management/module_routes.dart';

import '../../modules/state/status_management/module_entry.dart';
import '../../modules/ui/adsorption_line/module_entry.dart';
import '../../modules/ui/download_animation/module_entry.dart';
import '../../modules/ui/download_animation/module_routes.dart';
import '../../modules/ui/font_picker/module_entry.dart';
import '../../modules/ui/font_picker/module_routes.dart';
import '../../modules/ui/gcode_visualizer/module_entry.dart';
import '../../modules/popup_table/popup_widgets/module_entry.dart';
import '../../modules/popup_table/popup_list_interaction/module_entry.dart';
import '../../modules/popup_table/popup_list_interaction/module_routes.dart';
import '../../modules/popup_table/scroll_table/module_entry.dart';
import '../../modules/popup_table/overlay_follow_compare/module_entry.dart';

import '../../modules/platform/dio_interceptor/module_entry.dart';
import '../../modules/platform/dio_interceptor/module_routes.dart';
import '../../modules/platform/file_picker/module_entry.dart';
import '../../modules/platform/online_video_player/module_entry.dart';
import '../../modules/platform/usb_detector/module_entry.dart';
import '../../modules/state/local_persistence/module_entry.dart';
import '../../modules/platform/webview/module_entry.dart';

// ==================== 状态管理子路由（模块内部已定义映射） ====================

List<GoRoute> _buildStatusManageRoutes() => StatusManagementRoutes
    .routes
    .entries
    .map(
      (entry) => GoRoute(
        path: entry.key.startsWith('/') ? entry.key.substring(1) : entry.key,
        builder: (context, state) => entry.value(context),
      ),
    )
    .toList();

// ==================== 模块注册 ====================

final List<ModuleEntry> _modules = [
  // 基础机制
  ModuleEntry(
    title: '三棵树与生命周期',
    path: '/tree-state',
    subtitle: '理解 Widget/Element/RenderObject 的关系与重建机制',
    category: ModuleCategory.basic,
    difficulty: Difficulty.beginner,
    concepts: ['Widget 树', 'Element 树', 'RenderObject', '生命周期'],
    estimatedMinutes: 30,
    status: ModuleStatus.recommended,
    builder: (context) => const TreeStateEntry(),
    routes: TreeStateRoutes.routes,
  ),
  ModuleEntry(
    title: '事件循环与微任务',
    path: '/microtask',
    subtitle: '掌握 Dart 事件循环中微任务队列与事件队列的执行顺序',
    category: ModuleCategory.basic,
    difficulty: Difficulty.beginner,
    concepts: ['Microtask', 'Event Queue', 'async/await', 'Zone'],
    estimatedMinutes: 25,
    status: ModuleStatus.recommended,
    builder: (context) => const MicrotaskEntry(),
    routes: MicrotaskRoutes.routes,
  ),
  ModuleEntry(
    title: '防抖与节流',
    path: '/debounce-throttle',
    subtitle: '对比防抖和节流的执行时序，理解适用场景',
    category: ModuleCategory.basic,
    difficulty: Difficulty.beginner,
    concepts: ['Debouncer', 'Throttle', 'Timer'],
    estimatedMinutes: 15,
    status: ModuleStatus.ready,
    builder: (context) => const DebounceThrottleEntry(),
  ),

  // 异步并发
  ModuleEntry(
    title: 'Stream 订阅机制',
    path: '/stream-subscription',
    subtitle: '学习单订阅流与广播流的区别及使用场景',
    category: ModuleCategory.async,
    difficulty: Difficulty.intermediate,
    concepts: ['StreamController', '单订阅', '广播流', 'Stream 变换'],
    estimatedMinutes: 30,
    status: ModuleStatus.recommended,
    builder: (context) => const StreamSubscriptionEntry(),
    routes: StreamSubscriptionRoutes.routes,
  ),
  ModuleEntry(
    title: 'Isolate 并发对比',
    path: '/isolate-basic',
    subtitle: '对比主线程与 Isolate 执行耗时计算对 UI 流畅度的影响',
    category: ModuleCategory.async,
    difficulty: Difficulty.intermediate,
    concepts: ['Isolate', 'SendPort', 'ReceivePort', '性能优化'],
    estimatedMinutes: 20,
    status: ModuleStatus.ready,
    builder: (context) => const IsolateTestEntry(),
    routes: IsolateTestRoutes.routes,
  ),
  ModuleEntry(
    title: '多任务 Isolate 管理器',
    path: '/isolate-stream',
    subtitle: '使用 Isolate 并行处理多任务，通过 Stream 实时上报进度',
    category: ModuleCategory.async,
    difficulty: Difficulty.advanced,
    concepts: ['Isolate.spawn', '多任务', '进度上报', '暂停/恢复'],
    estimatedMinutes: 35,
    status: ModuleStatus.ready,
    builder: (context) => const IsolateStreamEntry(),
  ),

  // 状态管理
  ModuleEntry(
    title: '状态管理演进',
    path: '/status-management',
    subtitle: '串联 setState、Provider、Riverpod、Bloc，对比不同方案',
    category: ModuleCategory.state,
    difficulty: Difficulty.intermediate,
    concepts: ['Provider', 'Riverpod', 'Bloc', '状态提升', 'FutureProvider'],
    estimatedMinutes: 45,
    status: ModuleStatus.recommended,
    builder: (context) => const StatusManageEntry(),
    routes: _buildStatusManageRoutes(),
  ),
  ModuleEntry(
    title: 'Flutter IoC 容器',
    path: '/flutter-ioc',
    subtitle: '自研 IoC 容器实现，支持单例/瞬态/作用域生命周期',
    category: ModuleCategory.state,
    difficulty: Difficulty.advanced,
    concepts: ['IoC', '依赖注入', '生命周期', '作用域'],
    estimatedMinutes: 30,
    status: ModuleStatus.ready,
    builder: (context) => const FlutterIocEntry(),
  ),
  ModuleEntry(
    title: '本地持久化',
    path: '/local-persistence',
    subtitle: '使用 shared_preferences 持久化设置项与计数器，理解异步读取与状态恢复',
    category: ModuleCategory.state,
    difficulty: Difficulty.intermediate,
    concepts: ['shared_preferences', '键值存储', '异步读取', '状态恢复', '测试替身'],
    estimatedMinutes: 25,
    status: ModuleStatus.ready,
    builder: (context) => const LocalPersistenceEntry(),
  ),

  // UI 与动效
  ModuleEntry(
    title: 'G-code 解析与轨迹动画',
    path: '/gcode-visualizer',
    subtitle: '解析 G-code 指令，绘制刀路轨迹并用动画展示执行过程',
    category: ModuleCategory.ui,
    difficulty: Difficulty.advanced,
    concepts: ['G-code', 'Parser', 'CustomPaint', 'PathMetric', '动画控制'],
    estimatedMinutes: 45,
    status: ModuleStatus.ready,
    // gcode_core v0.2.0-dev.1 validates macOS GPU rendering only.
    supportedPlatforms: {TargetPlatform.macOS},
    builder: (context) => const GcodeVisualizerEntry(),
  ),
  ModuleEntry(
    title: '智能吸附线画板',
    path: '/adsorption-line',
    subtitle: '类似设计工具的对齐吸附功能，学习自定义绘制与手势',
    category: ModuleCategory.ui,
    difficulty: Difficulty.advanced,
    concepts: ['CustomPaint', '手势检测', '吸附算法', '状态管理'],
    estimatedMinutes: 40,
    status: ModuleStatus.ready,
    builder: (context) => const AdsorptionLineEntry(),
  ),
  ModuleEntry(
    title: '下载飞入动效',
    path: '/download-animation',
    subtitle: '三种实现方式对比：Custom View / CustomPaint / Overlay',
    category: ModuleCategory.ui,
    difficulty: Difficulty.intermediate,
    concepts: ['Tween 动画', 'CustomPaint', 'OverlayEntry', '动画配置'],
    estimatedMinutes: 30,
    status: ModuleStatus.ready,
    builder: (context) => const DownloadAnimationEntry(),
    routes: DownloadAnimationRoutes.routes,
  ),
  ModuleEntry(
    title: '字体选择器',
    path: '/font-picker',
    subtitle: '命名列表中直观对比不同字体族与字重样式，并通过文件选择器加载本地字体',
    category: ModuleCategory.ui,
    difficulty: Difficulty.intermediate,
    concepts: [
      'fontFamily',
      'TextStyle',
      '字重',
      '字距',
      '字体 fallback',
      '平台字体',
      'FontLoader',
      '中台复用',
    ],
    estimatedMinutes: 30,
    status: ModuleStatus.ready,
    builder: (context) => const FontPickerEntry(),
    routes: FontPickerRoutes.routes,
  ),

  // 弹窗与列表
  ModuleEntry(
    title: '弹窗合集',
    path: '/popup-widgets',
    subtitle: '全面展示 Flutter 中的对话框、底部抽屉、菜单等弹窗类型',
    category: ModuleCategory.popupTable,
    difficulty: Difficulty.beginner,
    concepts: ['AlertDialog', 'BottomSheet', 'Overlay', 'ContextMenu'],
    estimatedMinutes: 20,
    status: ModuleStatus.ready,
    builder: (context) => const PopWidgetEntry(),
  ),
  ModuleEntry(
    title: '弹窗与列表交互',
    path: '/popup-list-interaction',
    subtitle: 'Flutter 弹窗组件与二维滚动表格的综合演示',
    category: ModuleCategory.popupTable,
    difficulty: Difficulty.beginner,
    concepts: ['Dialog', 'BottomSheet', 'Overlay', 'TableView', '二维滚动'],
    estimatedMinutes: 25,
    status: ModuleStatus.ready,
    builder: (context) => const PopupListInteractionEntry(),
    routes: PopupListInteractionRoutes.routes,
  ),
  ModuleEntry(
    title: '二维滚动表格',
    path: '/scroll-table',
    subtitle: '使用 two_dimensional_scrollables 实现固定表头的表格',
    category: ModuleCategory.popupTable,
    difficulty: Difficulty.beginner,
    concepts: ['TableView', '固定表头', '二维滚动'],
    estimatedMinutes: 15,
    status: ModuleStatus.ready,
    builder: (context) => const ScrollTableEntry(),
  ),
  ModuleEntry(
    title: 'Overlay 跟随方案对照组',
    path: '/overlay-compare',
    subtitle: '对比 CompositedTransformFollower 与 markNeedsBuild 两种浮层跟随方案',
    category: ModuleCategory.popupTable,
    difficulty: Difficulty.intermediate,
    concepts: [
      'Overlay',
      'LayerLink',
      'CompositedTransformFollower',
      'markNeedsBuild',
      'ScrollController',
    ],
    estimatedMinutes: 30,
    status: ModuleStatus.ready,
    builder: (context) => const OverlayFollowCompareEntry(),
  ),

  // 网络与平台
  ModuleEntry(
    title: 'Dio 拦截器链路',
    path: '/dio-interceptor',
    subtitle: 'Auth/Error/Retry/Log 拦截器 + 本地 Mock Server 实战',
    category: ModuleCategory.platform,
    difficulty: Difficulty.intermediate,
    concepts: ['Dio', '拦截器', 'Token 刷新', 'Mock Server', '重试机制'],
    estimatedMinutes: 35,
    status: ModuleStatus.ready,
    // Native-only: the teaching backend starts a dart:io HttpServer on localhost.
    supportedPlatforms: {
      TargetPlatform.android,
      TargetPlatform.iOS,
      TargetPlatform.fuchsia,
      TargetPlatform.linux,
      TargetPlatform.macOS,
      TargetPlatform.windows,
    },
    builder: (context) => const InterceptorTestEntry(),
    routes: InterceptorTestRoutes.routes,
  ),
  ModuleEntry(
    title: 'USB 设备检测',
    path: '/usb-detector',
    subtitle: 'Android USB 设备检测与状态监控',
    category: ModuleCategory.platform,
    difficulty: Difficulty.intermediate,
    concepts: ['Android USB', 'MethodChannel', 'Stream 广播', '设备扫描'],
    estimatedMinutes: 25,
    status: ModuleStatus.ready,
    // Android-only: Windows 原生插件已移除，目录显示不可用、路由不注册
    supportedPlatforms: {TargetPlatform.android},
    builder: (context) => const UsbDetectorEntry(),
  ),
  ModuleEntry(
    title: '文件选择器',
    path: '/file-picker',
    subtitle: '复用 file_picker_bridge 中台能力，演示扩展过滤、取消分支与平台差异',
    category: ModuleCategory.platform,
    difficulty: Difficulty.intermediate,
    concepts: ['FilePickerService', 'MethodChannel', '平台桥接', '扩展名过滤', '取消分支'],
    estimatedMinutes: 20,
    status: ModuleStatus.ready,
    supportedPlatforms: {TargetPlatform.macOS, TargetPlatform.windows},
    builder: (context) => const FilePickerEntry(),
  ),
  ModuleEntry(
    title: '在线视频播放',
    path: '/online-video-player',
    subtitle: '使用 video_player 播放在线 HTTP 视频流并操控播放参数',
    category: ModuleCategory.platform,
    difficulty: Difficulty.intermediate,
    concepts: [
      'video_player',
      '平台播放器',
      'HTTP 流',
      '播放控制',
      '倍速',
      'Controller 生命周期',
    ],
    estimatedMinutes: 35,
    status: ModuleStatus.ready,
    supportedPlatforms: {TargetPlatform.macOS, TargetPlatform.windows},
    builder: (context) => const OnlineVideoPlayerEntry(),
  ),
  ModuleEntry(
    title: '网页容器与跨平台导航',
    path: '/webview',
    subtitle: '学习 Android、macOS、Windows 网页导航与生命周期',
    category: ModuleCategory.platform,
    difficulty: Difficulty.intermediate,
    concepts: ['WebView', 'WebView2', '加载进度', '生命周期'],
    estimatedMinutes: 30,
    status: ModuleStatus.ready,
    // Android/macOS use webview_flutter; Windows uses WebView2.
    supportedPlatforms: {
      TargetPlatform.android,
      TargetPlatform.macOS,
      TargetPlatform.windows,
    },
    builder: (context) => const WebViewEntry(),
  ),
];

final List<GoRoute> _routes = [
  GoRoute(
    path: '/',
    builder: (context, state) => ModuleHomePage(modules: _modules),
  ),
  for (final module in availableModules(_modules))
    GoRoute(
      path: module.path,
      builder: (context, state) => module.builder(context),
      routes: module.routes,
    ),
];

class AppRouteTable {
  static List<GoRoute> get routes => _routes;
  static List<ModuleEntry> get modules => _modules;
}
